"""empty message

Revision ID: 910942f3600f
Revises: 8e952dd9dc91
Create Date: 2023-08-03 17:29:35.231128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910942f3600f'
down_revision = '8e952dd9dc91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('gender', sa.String(length=250), nullable=False),
    sa.Column('age', sa.String(length=250), nullable=False),
    sa.Column('breed', sa.String(length=250), nullable=False),
    sa.Column('image', sa.String(length=250), nullable=False),
    sa.Column('info', sa.String(length=250), nullable=False),
    sa.Column('detail', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dog.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    op.drop_table('favorite')
    op.drop_table('dog')
    # ### end Alembic commands ###
